# Generated by Django 2.2.6 on 2019-11-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='rest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rest',
            name='rating',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='itemName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='itemPrice',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='itemRating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='restId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rest',
            name='phone',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rest',
            name='restName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rest',
            name='restPrice',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rest',
            name='restRating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rest',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rest',
            name='zipcode',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
