# Generated by Django 2.2.6 on 2019-11-12 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0003_auto_20191105_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemPrice',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemRating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='restId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppAPI.Rest'),
        ),
        migrations.AlterField(
            model_name='rest',
            name='phone',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rest',
            name='restName',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='rest',
            name='restPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rest',
            name='restRating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rest',
            name='website',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='rest',
            name='zipcode',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='userEmail',
            field=models.CharField(default=' ', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=300, null=True)),
                ('rating', models.PositiveIntegerField()),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAPI.Item')),
                ('restId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAPI.Rest')),
                ('userEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAPI.User')),
            ],
        ),
    ]
