# Generated by Django 2.2.6 on 2019-11-12 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0004_auto_20191111_2008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ratings',
            new_name='Rating',
        ),
    ]
