# Generated by Django 2.2.6 on 2019-11-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0005_auto_20191111_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemPrice',
            field=models.FloatField(default=0),
        ),
    ]
