# Generated by Django 2.2.6 on 2019-11-13 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0006_auto_20191111_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='itemId',
        ),
    ]
