# Generated by Django 2.2.6 on 2019-11-17 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0007_remove_rating_itemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='restId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='AppAPI.Rest'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='userEmail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='AppAPI.User'),
        ),
    ]
