# Generated by Django 2.2.7 on 2019-11-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0010_rest_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rest',
            name='restRating',
        ),
    ]
