# Generated by Django 2.2.7 on 2019-11-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0014_rest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='banner',
            field=models.ImageField(default='/media/ic_launcher_img_foreground.jpg', null=True, upload_to=''),
        ),
    ]
