# Generated by Django 2.2.7 on 2019-11-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0015_auto_20191121_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='category',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
