# Generated by Django 2.2.7 on 2019-11-26 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0016_auto_20191121_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=300, null=True)),
                ('rating', models.PositiveIntegerField()),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAPI.Item')),
                ('restId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAPI.Rest')),
                ('userEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAPI.User')),
            ],
        ),
    ]
