# Generated by Django 2.2.7 on 2019-12-04 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0017_ratingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=300, null=True)),
                ('ratingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAPI.Rating')),
            ],
        ),
    ]
